name: ticketing_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  freezed: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  dio: ^4.0.4
  http: ^0.13.4
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  freezed_annotation: ^1.1.0
  json_serializable: ^6.0.3

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/